version: "3.9"  # optional since v1.27.0
services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}

  dev:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - "web"
    volumes:
      - type: bind
        source: ./service
        target: /opt/service
        consistency: cached
      - type: bind
        source: ./tests
        target: /opt/tests
        consistency: cached
      - ${PWD}/poetry.lock:/opt/pysetup/poetry.lock
      - ${PWD}/pyproject.toml:/opt/pysetup/pyproject.toml

