image_locations = {
  "Aaron Jones": "https://upload.wikimedia.org/wikipedia/commons/9/99/Aaron_Jones_%2843964183845%29.jpg",
  "Alvin Kamara": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Alvin_Kamara_2019.png/512px-Alvin_Kamara_2019.png",
  "Baltimore Ravens": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Baltimore_Ravens_mascot_Poe_Nov_2014.jpg",
  "Dalvin Cook": "https://upload.wikimedia.org/wikipedia/commons/6/67/Dalvin_Cook_2014.jpg",
  "Damien Williams": "https://upload.wikimedia.org/wikipedia/commons/6/61/Damien_Williams_%28running_back%29_2019.JPG",
  "Davante Adams": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Davante_Adams_2017.jpg",
  "DeAndre Hopkins": "",
  "Deebo Samuel": "",
  "Drew Brees": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Drew_Brees_2015.jpg/256px-Drew_Brees_2015.jpg",
  "Emmanuel Sanders": "",
  "George Kittle": "",
  "Harrison Butker": "",
  "Jacob Hollister": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Jacob_Hollister.JPG",
  "James White": "",
  "Jared Cook": "",
  "Jason Myers": "",
  "Jimmy Garoppolo": "",
  "Julian Edelman": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Julian_Edelman_2014_%28square_crop%29.JPG/512px-Julian_Edelman_2014_%28square_crop%29.JPG",
  "Justin Tucker": "",
  "Lamar Jackson": "",
  "Mark Andrews": "",
  "Mark Ingram": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Alvin_Kamara_2019.png/512px-Alvin_Kamara_2019.png",
  "Marquise Brown": "",
  "Marshawn Lynch": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Marshawn_Lynch_2014.jpg",
  "Michael Thomas": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Michael_Thomas_2018.png",
  "New England Patriots": "",
  "New Orleans Saints": "",
  "Nick Folk": "https://upload.wikimedia.org/wikipedia/commons/8/87/Folk_with_the_Patriots_in_2019.jpg",
  "Raheem Mostert": "",
  "Robbie Gould": "",
  "Russell Wilson": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Russell_Wilson_%28cropped%29.jpg",
  "San Francisco 49ers": "",
  "Seattle Seahawks": "",
  "Sony Michel": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Sony_Michel_Jan_2018.jpg",
  "Stefon Diggs": "",
  "Travis Kelce": "",
  "Tyler Lockett": "",
  "Tyreek Hill": "",
  "Wil Lutz": ""
}
