image_locations = {
"Mark Ingram": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Alvin_Kamara_2019.png/512px-Alvin_Kamara_2019.png",
"Drew Brees": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Drew_Brees_2015.jpg/256px-Drew_Brees_2015.jpg",
"Alvin Kamara": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Alvin_Kamara_2019.png/512px-Alvin_Kamara_2019.png",
"Sony Michel": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Sony_Michel_Jan_2018.jpg",
"Michael Thomas": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Michael_Thomas_2018.png",
"Julian Edelman": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Julian_Edelman_2014_%28square_crop%29.JPG/512px-Julian_Edelman_2014_%28square_crop%29.JPG",
"Jacob Hollister": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Jacob_Hollister.JPG",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
"": """""",
}
