image_locations = {
  "Aaron Jones": "https://upload.wikimedia.org/wikipedia/commons/9/99/Aaron_Jones_%2843964183845%29.jpg",
  "Alvin Kamara": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Alvin_Kamara_2019.png/512px-Alvin_Kamara_2019.png",
  "Baltimore Ravens": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Baltimore_Ravens_mascot_Poe_Nov_2014.jpg",
  "Dalvin Cook": "https://upload.wikimedia.org/wikipedia/commons/6/67/Dalvin_Cook_2014.jpg",
  "Damien Williams": "https://upload.wikimedia.org/wikipedia/commons/6/61/Damien_Williams_%28running_back%29_2019.JPG",
  "Davante Adams": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Davante_Adams_2017.jpg",
  "DeAndre Hopkins": "https://upload.wikimedia.org/wikipedia/commons/1/17/DeAndre_Hopkins_2018.JPG",
  "Deebo Samuel": "https://upload.wikimedia.org/wikipedia/commons/9/95/Deebo_Samuel.jpg",
  "Drew Brees": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Drew_Brees_2015.jpg/256px-Drew_Brees_2015.jpg",
  "Emmanuel Sanders": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Emmanuel_Sanders_2018.jpg",
  "George Kittle": "https://upload.wikimedia.org/wikipedia/commons/6/68/Kittle_with_fans_in_2019.jpg",
  "Harrison Butker": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Harrison_Butker.JPG",
  "Jacob Hollister": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Jacob_Hollister.JPG",
  "James White": "https://upload.wikimedia.org/wikipedia/commons/2/20/James_White_%28running_back%29.JPG",
  "Jared Cook": "https://upload.wikimedia.org/wikipedia/commons/4/44/Jared_Cook.jpg",
  "Jason Myers": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Blitz_Seattle_Seahawks_Mascot.jpg",
  "Jimmy Garoppolo": "https://upload.wikimedia.org/wikipedia/commons/7/7e/2018_Jimmy_Garoppolo_%28cropped%29.jpg",
  "Julian Edelman": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Julian_Edelman_2014_%28square_crop%29.JPG/512px-Julian_Edelman_2014_%28square_crop%29.JPG",
  "Justin Tucker": "https://upload.wikimedia.org/wikipedia/commons/d/da/Justin_Tucker_%28cropped%29.jpg",
  "Lamar Jackson": "https://upload.wikimedia.org/wikipedia/commons/a/ac/Lamar_Jackson_vs._Bengals_2018.jpg",
  "Mark Andrews": "https://upload.wikimedia.org/wikipedia/commons/2/2d/Mark_Andrews_%28American_football%29.jpg",
  "Mark Ingram": "https://upload.wikimedia.org/wikipedia/commons/0/02/Mark_Ingram%2C_Jr._at_the_White_House_2010-03-08_3.jpg",
  "Marquise Brown": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Baltimore_Ravens_mascot_Poe_Nov_2014.jpg",
  "Marshawn Lynch": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Marshawn_Lynch_2014.jpg",
  "Michael Thomas": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Michael_Thomas_2018.png",
  "New England Patriots": "https://upload.wikimedia.org/wikipedia/commons/3/3b/New_England_Patriots_NE_logo.png",
  "New Orleans Saints": "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg",
  "Nick Folk": "https://upload.wikimedia.org/wikipedia/commons/8/87/Folk_with_the_Patriots_in_2019.jpg",
  "Raheem Mostert": "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg",
  "Robbie Gould": "https://upload.wikimedia.org/wikipedia/commons/8/89/Robbie_Gould_2017.jpg",
  "Russell Wilson": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Russell_Wilson_%28cropped%29.jpg",
  "San Francisco 49ers": "https://upload.wikimedia.org/wikipedia/commons/3/3a/San_Francisco_49ers_logo.svg",
  "Seattle Seahawks": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Blitz_Seattle_Seahawks_Mascot.jpg",
  "Sony Michel": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Sony_Michel_Jan_2018.jpg",
  "Stefon Diggs": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Stefon_Diggs_%2826600152089%29.jpg",
  "Travis Kelce": "https://upload.wikimedia.org/wikipedia/commons/c/ca/Travis_Kelce.JPG",
  "Tyler Lockett": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Tyler_Lockett_2016_Pro_Bowl.jpg",
  "Tyreek Hill": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Tyreek_Hill.png",
  "Wil Lutz": "https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg"
}
